#!/bin/bash
# TikTok Sandbox Diagnostic Script
# Checks for common sandbox app issues

echo ""
echo "🔍 TikTok Sandbox App Diagnostic"
echo "=================================="
echo ""

# Parse the error URL
ERROR_URL="https://www.tiktok.com/v2/auth/authorize/?client_key=sbawd3rphncujty972&scope=user.info.basic%2Cuser.info.profile%2Cvideo.list&response_type=code&redirect_uri=https%3A%2F%2Fsubsocial-justice-detersively.ngrok-free.dev%2Fapi%2Fauth%2Ftiktok%2Fcallback&state=p63k5e6lxp&error=unauthorized_client&error_type=client_key"

echo "📋 Error Details:"
echo "   Error: unauthorized_client"
echo "   Error Type: client_key"
echo "   Client Key: sbawd3rphncujty972"
echo ""

echo "🎯 Most Likely Causes for Sandbox Apps:"
echo ""
echo "1. ⚠️  TEST ACCOUNT NOT WHITELISTED"
echo "   → Sandbox apps ONLY work with whitelisted test TikTok accounts"
echo "   → The TikTok account you're trying to log in with may not be whitelisted"
echo "   → The working PC might be logged into a whitelisted account"
echo ""
echo "   Fix: In TikTok Developer Portal → Sandbox settings:"
echo "   - Add your test TikTok account email/phone"
echo "   - That TikTok account must exist and be logged in during OAuth"
echo ""

echo "2. ⚠️  'APPLY CHANGES' NOT CLICKED"
echo "   → After adding redirect URIs, you MUST click 'Apply changes' (red button)"
echo "   → Changes are not saved until you click that button"
echo ""
echo "   Fix: Click the red 'Apply changes' button in top right"
echo ""

echo "3. ⚠️  PROPAGATION DELAY"
echo "   → TikTok can take 5-10 minutes to propagate settings"
echo "   → Especially for sandbox apps"
echo ""
echo "   Fix: Wait 10-15 minutes after clicking 'Apply changes'"
echo ""

echo "4. ⚠️  BROWSER/COOKIE ISSUE"
echo "   → Old cached authorization attempts"
echo "   → Different TikTok account logged in on different PCs"
echo ""
echo "   Fix: Try incognito/private browsing mode"
echo ""

echo "=================================="
echo ""
echo "🔍 Detailed Troubleshooting Steps:"
echo ""

echo "STEP 1: Verify TikTok Developer Portal Settings"
echo "   → Go to: https://developers.tiktok.com/apps/"
echo "   → Select: Academia Sandbox"
echo "   → Check Products → Login Kit → Redirect URI:"
echo "     ✓ https://subsocial-justice-detersively.ngrok-free.dev/api/auth/tiktok/callback"
echo "     ✓ https://subsocial-justice-detersively.ngrok-free.dev"
echo "     ✓ https://academia-blond-chi.vercel.app/api/auth/tiktok/callback"
echo ""

echo "STEP 2: Check Sandbox Settings (CRITICAL!)"
echo "   → Click 'Sandbox settings' in left sidebar"
echo "   → Check 'Test accounts' section"
echo "   → Verify YOUR TikTok account is listed"
echo "   → If not, add it:"
echo "     - Enter your TikTok account email or phone"
echo "     - Send invitation"
echo "     - Accept invitation from TikTok app"
echo ""

echo "STEP 3: Apply Changes and Wait"
echo "   → Click red 'Apply changes' button (top right)"
echo "   → Wait 10-15 minutes"
echo "   → Don't test immediately!"
echo ""

echo "STEP 4: Test with Whitelisted Account"
echo "   → IMPORTANT: You must be logged into TikTok with the whitelisted test account"
echo "   → On the failing PC:"
echo "     1. Go to tiktok.com"
echo "     2. Log out of current TikTok account"
echo "     3. Log in with the whitelisted test account"
echo "     4. Then try OAuth login from your app"
echo ""

echo "STEP 5: Try Incognito Mode"
echo "   → Open incognito/private browser window"
echo "   → Go to your ngrok URL"
echo "   → Try login"
echo "   → When redirected to TikTok, log in with whitelisted test account"
echo ""

echo "=================================="
echo ""
echo "🎯 Quick Check: Compare Working vs Non-Working PC"
echo ""
echo "Working PC (Vercel):"
echo "   - What TikTok account are you logged in with?"
echo "   - Is it a whitelisted test account?"
echo ""
echo "Failing PC (ngrok):"
echo "   - What TikTok account are you logged in with?"
echo "   - Is it the SAME account as working PC?"
echo "   - Is it whitelisted in sandbox settings?"
echo ""

echo "=================================="
echo ""
echo "💡 Pro Tips:"
echo ""
echo "1. Sandbox apps are for testing ONLY"
echo "   - Work with whitelisted accounts only"
echo "   - Limited to specific test users"
echo "   - If you want any TikTok user to log in, use Production mode"
echo ""
echo "2. To move to Production:"
echo "   - Click 'Production' tab in TikTok portal"
echo "   - Submit app for review"
echo "   - Provide privacy policy URL"
echo "   - Once approved, any TikTok user can log in"
echo ""
echo "3. For now (Sandbox):"
echo "   - Make sure you're testing with whitelisted accounts"
echo "   - Add all developers' TikTok accounts as test users"
echo "   - Everyone must be logged into their whitelisted account when testing"
echo ""

echo "=================================="
echo ""
echo "🆘 If Still Not Working:"
echo ""
echo "Run this command and share the output:"
echo "   curl -I 'https://subsocial-justice-detersively.ngrok-free.dev/api/auth/tiktok'"
echo ""
echo "Also check:"
echo "   1. Is 'Apply changes' button still visible? (If yes, you didn't save!)"
echo "   2. Screenshot of Sandbox settings → Test accounts section"
echo "   3. Which TikTok account email is logged in on failing PC"
echo ""

echo "=================================="
echo ""
